package org.fiuba.guitapp.exception;

public enum ErrorCode {
    MAIL_ALREADY_USED,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    INCOME_NOT_FOUND,
    INCOME_ACCESS_DENIED,
    RECURRING_INCOME_NOT_FOUND,
    RECURRING_INCOME_ACCESS_DENIED,
    EXPENSE_NOT_FOUND,
    EXPENSE_ACCESS_DENIED,
    INVALID_OTP,
    OTP_EXPIRED,
    USER_ALREADY_VERIFIED,
    VALIDATION_FAILED,
    RATE_LIMIT_EXCEEDED,
    UNKNOWN_ERROR,
    INVALID_PERIOD,
    CATEGORY_RULE_DUPLICATED,
    CATEGORY_RULE_INVALID_CATEGORY,
    CATEGORY_RULE_NOT_FOUND
}
